// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ScoreHub_Infrastructure;

#nullable disable

namespace ScoreHub_Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260204150551_nullPossibleMkn")]
    partial class nullPossibleMkn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ScoreHub_Domain.Entities.MKN.LessonMkn", b =>
                {
                    b.Property<Guid>("LessonMknId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AdditionalCoefficient")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsStudentAttended")
                        .HasColumnType("boolean");

                    b.Property<int>("LessonMknNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("MknId")
                        .HasColumnType("uuid");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.PrimitiveCollection<List<double>>("Scores")
                        .IsRequired()
                        .HasColumnType("double precision[]");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("LessonMknId");

                    b.HasIndex("MknId");

                    b.ToTable("LessonMkns");
                });

            modelBuilder.Entity("ScoreHub_Domain.Entities.MKN.Mkn", b =>
                {
                    b.Property<Guid>("MknId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("FinalMark")
                        .HasColumnType("double precision");

                    b.Property<double>("FinalScores")
                        .HasColumnType("double precision");

                    b.Property<double>("FirstModuleScores")
                        .HasColumnType("double precision");

                    b.Property<double>("RawMark")
                        .HasColumnType("double precision");

                    b.Property<double>("RawScores")
                        .HasColumnType("double precision");

                    b.Property<double>("SecondModuleScores")
                        .HasColumnType("double precision");

                    b.Property<double>("ThirdModuleScores")
                        .HasColumnType("double precision");

                    b.HasKey("MknId");

                    b.ToTable("Mkns");
                });

            modelBuilder.Entity("ScoreHub_Domain.Entities.Student", b =>
                {
                    b.Property<Guid>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("MknId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patronymic")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StudentId");

                    b.HasIndex("MknId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("ScoreHub_Domain.Entities.MKN.LessonMkn", b =>
                {
                    b.HasOne("ScoreHub_Domain.Entities.MKN.Mkn", null)
                        .WithMany("Lessons")
                        .HasForeignKey("MknId");
                });

            modelBuilder.Entity("ScoreHub_Domain.Entities.Student", b =>
                {
                    b.HasOne("ScoreHub_Domain.Entities.MKN.Mkn", "Mkn")
                        .WithMany()
                        .HasForeignKey("MknId");

                    b.Navigation("Mkn");
                });

            modelBuilder.Entity("ScoreHub_Domain.Entities.MKN.Mkn", b =>
                {
                    b.Navigation("Lessons");
                });
#pragma warning restore 612, 618
        }
    }
}
